name: TTRPG Convert CLI
release:
  current-version: 2.3.5
  next-version: 2.3.5
  snapshot-version: 299-SNAPSHOT
build:
  artifact: ttrpg-convert-cli
jitpack:
  group: com.github.ebullient
  artifact: ttrpg-convert-cli
toggle: false
