name: TTRPG Convert CLI
release:
  current-version: 3.0.0
  next-version: 3.0.0
  snapshot-version: 299-SNAPSHOT
build:
  artifact: ttrpg-convert-cli
jitpack:
  group: com.github.ebullient
  artifact: ttrpg-convert-cli
toggle: false
