---
sources:
  book:
    - "XPHB"
    - "XDMG"
    - "MM"
    - "SCAG"
    - "TCE"
    - "XGE"
    - "VGM"
  adventure:
    - "WDH"
paths:
  compendium: "/compendium/"
  rules: "/compendium/rules/"
reprintBehavior: "newest"
useDiceRoller: true
yamlStatblocks: true
tagPrefix: "ttrpg-cli"
images:
  copyInternal: true
  internalRoot: "/app/data/5etools-img"
template:
  background: "examples/templates/tools5e/images-background2md.txt"
  item: "examples/templates/tools5e/images-item2md.txt"
  monster: "config/templates/monster2md-yamlStatblock-body-images.txt"
  object: "examples/templates/tools5e/object2md-yamlStatblock-body.txt"
  race: "examples/templates/tools5e/images-race2md.txt"
  spell: "examples/templates/tools5e/images-spell2md.txt"
  vehicle: "examples/templates/tools5e/images-vehicle2md.txt"
